<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/', 'middleware' => ['has_any_role:admin|chuyen-vien-so|truong-van-phong'],'as'=>'admin.'), function () {

    Route::get('kieuhopdongs', ['as'=> 'kieuhopdongs.index', 'uses' => 'Admin\Builder\KieuhopdongController@index']);
    Route::post('kieuhopdongs', ['as'=> 'kieuhopdongs.store', 'uses' => 'Admin\Builder\KieuhopdongController@store']);
    Route::get('kieuhopdongs/create', ['as'=> 'kieuhopdongs.create', 'uses' => 'Admin\Builder\KieuhopdongController@create']);
    Route::get('kieuhopdongs/sync-kind', ['as'=> 'kieuhopdongs.syncKind', 'uses' => 'Admin\Builder\KieuhopdongController@syncKind']);
    Route::get('kieuhopdongs/sync-kind-all', ['as'=> 'kieuhopdongs.syncAllKind', 'uses' => 'Admin\Builder\KieuhopdongController@syncAllKind']);

    Route::put('kieuhopdongs/{kieuhopdongs}', ['as'=> 'kieuhopdongs.update', 'uses' => 'Admin\Builder\KieuhopdongController@update']);
    Route::patch('kieuhopdongs/{kieuhopdongs}', ['as'=> 'kieuhopdongs.update', 'uses' => 'Admin\Builder\KieuhopdongController@update']);
    Route::get('kieuhopdongs/{id}/delete', array('as' => 'kieuhopdongs.delete', 'uses' => 'Admin\Builder\KieuhopdongController@getDelete'));
    Route::get('kieuhopdongs/{id}/confirm-delete', array('as' => 'kieuhopdongs.confirm-delete', 'uses' => 'Admin\Builder\KieuhopdongController@getModalDelete'));
    Route::get('kieuhopdongs/{kieuhopdongs}', ['as'=> 'kieuhopdongs.show', 'uses' => 'Admin\Builder\KieuhopdongController@show']);
    Route::get('kieuhopdongs/{kieuhopdongs}/edit', ['as'=> 'kieuhopdongs.edit', 'uses' => 'Admin\Builder\KieuhopdongController@edit']);

    });
/*
Route::group(array('prefix' => 'admin/', 'middleware' => ['has_any_role:admin|so-tu-phap'],'as'=>'admin.'), function () {

Route::get('kieuhopdongs', ['as'=> 'kieuhopdongs.index', 'uses' => 'Admin\Builder\KieuhopdongController@index']);
Route::post('kieuhopdongs', ['as'=> 'kieuhopdongs.store', 'uses' => 'Admin\Builder\KieuhopdongController@store']);
Route::get('kieuhopdongs/create', ['as'=> 'kieuhopdongs.create', 'uses' => 'Admin\Builder\KieuhopdongController@create']);
Route::put('kieuhopdongs/{kieuhopdongs}', ['as'=> 'kieuhopdongs.update', 'uses' => 'Admin\Builder\KieuhopdongController@update']);
Route::patch('kieuhopdongs/{kieuhopdongs}', ['as'=> 'kieuhopdongs.update', 'uses' => 'Admin\Builder\KieuhopdongController@update']);
Route::get('kieuhopdongs/{id}/delete', array('as' => 'kieuhopdongs.delete', 'uses' => 'Admin\Builder\KieuhopdongController@getDelete'));
Route::get('kieuhopdongs/{id}/confirm-delete', array('as' => 'kieuhopdongs.confirm-delete', 'uses' => 'Admin\Builder\KieuhopdongController@getModalDelete'));
Route::get('kieuhopdongs/{kieuhopdongs}', ['as'=> 'kieuhopdongs.show', 'uses' => 'Admin\Builder\KieuhopdongController@show']);
Route::get('kieuhopdongs/{kieuhopdongs}/edit', ['as'=> 'kieuhopdongs.edit', 'uses' => 'Admin\Builder\KieuhopdongController@edit']);

});

/*
Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('vaiTros', ['as'=> 'vaiTros.index', 'uses' => 'Admin\Builder\VaiTroController@index']);
Route::post('vaiTros', ['as'=> 'vaiTros.store', 'uses' => 'Admin\Builder\VaiTroController@store']);
Route::get('vaiTros/create', ['as'=> 'vaiTros.create', 'uses' => 'Admin\Builder\VaiTroController@create']);
Route::put('vaiTros/{vaiTros}', ['as'=> 'vaiTros.update', 'uses' => 'Admin\Builder\VaiTroController@update']);
Route::patch('vaiTros/{vaiTros}', ['as'=> 'vaiTros.update', 'uses' => 'Admin\Builder\VaiTroController@update']);
Route::get('vaiTros/{id}/delete', array('as' => 'vaiTros.delete', 'uses' => 'Admin\Builder\VaiTroController@getDelete'));
Route::get('vaiTros/{id}/confirm-delete', array('as' => 'vaiTros.confirm-delete', 'uses' => 'Admin\Builder\VaiTroController@getModalDelete'));
Route::get('vaiTros/{vaiTros}', ['as'=> 'vaiTros.show', 'uses' => 'Admin\Builder\VaiTroController@show']);
Route::get('vaiTros/{vaiTros}/edit', ['as'=> 'vaiTros.edit', 'uses' => 'Admin\Builder\VaiTroController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('vaiTros', ['as'=> 'vaiTros.index', 'uses' => 'Admin\Builder\VaiTroController@index']);
Route::post('vaiTros', ['as'=> 'vaiTros.store', 'uses' => 'Admin\Builder\VaiTroController@store']);
Route::get('vaiTros/create', ['as'=> 'vaiTros.create', 'uses' => 'Admin\Builder\VaiTroController@create']);
Route::put('vaiTros/{vaiTros}', ['as'=> 'vaiTros.update', 'uses' => 'Admin\Builder\VaiTroController@update']);
Route::patch('vaiTros/{vaiTros}', ['as'=> 'vaiTros.update', 'uses' => 'Admin\Builder\VaiTroController@update']);
Route::get('vaiTros/{id}/delete', array('as' => 'vaiTros.delete', 'uses' => 'Admin\Builder\VaiTroController@getDelete'));
Route::get('vaiTros/{id}/confirm-delete', array('as' => 'vaiTros.confirm-delete', 'uses' => 'Admin\Builder\VaiTroController@getModalDelete'));
Route::get('vaiTros/{vaiTros}', ['as'=> 'vaiTros.show', 'uses' => 'Admin\Builder\VaiTroController@show']);
Route::get('vaiTros/{vaiTros}/edit', ['as'=> 'vaiTros.edit', 'uses' => 'Admin\Builder\VaiTroController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('vaitros', ['as'=> 'vaitros.index', 'uses' => 'Admin\Builder\vaitroController@index']);
Route::post('vaitros', ['as'=> 'vaitros.store', 'uses' => 'Admin\Builder\vaitroController@store']);
Route::get('vaitros/create', ['as'=> 'vaitros.create', 'uses' => 'Admin\Builder\vaitroController@create']);
Route::put('vaitros/{vaitros}', ['as'=> 'vaitros.update', 'uses' => 'Admin\Builder\vaitroController@update']);
Route::patch('vaitros/{vaitros}', ['as'=> 'vaitros.update', 'uses' => 'Admin\Builder\vaitroController@update']);
Route::get('vaitros/{id}/delete', array('as' => 'vaitros.delete', 'uses' => 'Admin\Builder\vaitroController@getDelete'));
Route::get('vaitros/{id}/confirm-delete', array('as' => 'vaitros.confirm-delete', 'uses' => 'Admin\Builder\vaitroController@getModalDelete'));
Route::get('vaitros/{vaitros}', ['as'=> 'vaitros.show', 'uses' => 'Admin\Builder\vaitroController@show']);
Route::get('vaitros/{vaitros}/edit', ['as'=> 'vaitros.edit', 'uses' => 'Admin\Builder\vaitroController@edit']);

});*/


Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');
